export const dummyAgencies = [
  {
    agencyName: "Agency 1",
    approveTime: "...",
    authorizeAdminUsername: "admin1",
    authorizeStatus: "Approved",
    bankAccount: "...",
    bankName: "...",
    email: "agency1@example.com",
    image: "...",
    licenseNo: "...",
    phone: "123456789",
    username: "agency1",
  },
  {
    agencyName: "Agency 2",
    approveTime: "...",
    authorizeAdminUsername: "admin2",
    authorizeStatus: "Pending",
    bankAccount: "...",
    bankName: "...",
    email: "agency2@example.com",
    image: "...",
    licenseNo: "...",
    phone: "987654321",
    username: "agency2",
  },
  {
    agencyName: "Agency 3",
    approveTime: "...",
    authorizeAdminUsername: "admin3",
    authorizeStatus: "Rejected",
    bankAccount: "...",
    bankName: "...",
    email: "agency3@example.com",
    image: "...",
    licenseNo: "...",
    phone: "555555555",
    username: "agency3",
  },
];

export const dummyOneAgency = {
  amount: 50,
  method: "credit_card",
  status: "success",
  stripeID: "ch_1Hzy7v2eZvKYlo2CNQ5VLN0q",
  timestamp: "2024-04-19T12:30:00Z",
  tourId: 123,
  touristUsername: "john_doe",
  transactionId: 456789,
};
